### ISSUE TITLE
Email Login and Logout 

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#101]
## Description
To implement Email Login in the Initial Screen. Currently, it's resulting in null uid as shown below.

## Screenshots

<div class = "row">
<img src="https://user-images.githubusercontent.com/59333817/135727265-2f1adf77-e593-482b-8bf8-30329bc31855.png" 
 width = 45% />
<img src="https://user-images.githubusercontent.com/59333817/135727368-d77dc7aa-e41a-4601-8be0-bf03ae613337.png" 
  width = 45% />
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Initial screen : lib\screens\initial_screen.dart
2. Auth files: lib\services\auth.dart
3. Also implement the email log out when the user taps on the logout button.
4. Private profile: lib\screens\profile\private_profile.dart

## Additional data
None

**Comment by keyurgit45** [comment]
I can give it a try!

**Comment by Mohitmadhav** [comment]
Cool @keyurgit45, please can try to implement auth provider if you can. 
I'll make the state management easier.

**Comment by keyurgit45** [comment]
I can use firebase.instance.authstatechanged . for that can create a new class to manage these things ?
In main.dart wrapper class route will be given to initialroute.
![image](https://user-images.githubusercontent.com/75253653/135741145-d72765a1-7c66-42ea-9558-2cef8b5a6dfb.png)

**Comment by Mohitmadhav** [comment]
> I can use firebase.instance.authstatechanged . for that we can create a new class to manage these things ? In main.dart wrapper class route will be given to initialroute. @Mohitmadhav ![image](https://user-images.githubusercontent.com/75253653/135741145-d72765a1-7c66-42ea-9558-2cef8b5a6dfb.png)

Okay @keyurgit45, also make sure to check the expiry time for logging in (Like if a user opens the app after 1 week, then he'll again have to log in). And remove the Wrapper Constructor if you're not using the key somewhere else

**Comment by keyurgit45** [comment]
@Mohitmadhav  I have made the changes. Log in and log out are working fine. also in the sign-in method, I added the makeUserDataFromAuthUser() method which I forgot to add in prev PR. but I haven't implemented that expiry time for logging because I don't know how to implement that . Should I make a PR?

**Comment by keyurgit45** [comment]
For the expiry time for logging in feature, can we store the time each time when a user opens the app in shared pref and checks if it is been a 1 week or not if yes then it will log out else the user will be on the home screen?

**Comment by Mohitmadhav** [comment]
> For the expiry time for logging in feature, can we store the time each time when a user opens the app in shared pref and checks if it is been a 1 week or not if yes then it will log out else the user will be on the home screen?

In general how long does the user can stay logged in (1 hr) if he doesn't open the app for a few days, which I don't know?

No , don't use shared preferences, I have already setup Flutter Secure Storage Package , have a look at that

**Comment by keyurgit45** [comment]
official docs : Firebase Authentication sessions are long lived. Every time a user signs in, the user credentials are sent to the Firebase Authentication backend and exchanged for a Firebase ID token (a JWT) and refresh token. Firebase ID tokens are short lived and last for an hour; the refresh token can be used to retrieve new ID tokens. Refresh tokens expire only when one of the following occurs:

The user is deleted
The user is disabled
A major account change is detected for the user. This includes events like password or email address updates.

also take a look at my previous comment also.

**Comment by Mohitmadhav** [comment]
> official docs : Firebase Authentication sessions are long lived. Every time a user signs in, the user credentials are sent to the Firebase Authentication backend and exchanged for a Firebase ID token (a JWT) and refresh token. Firebase ID tokens are short lived and last for an hour; the refresh token can be used to retrieve new ID tokens. Refresh tokens expire only when one of the following occurs:
> 
> The user is deleted The user is disabled A major account change is detected for the user. This includes events like password or email address updates.
> 
> also take a look at my previous comment also.

Yeah, I read that too, and also your previous comment. 
So don't use shared preference but go for Flutter Secure storage package: https://pub.dev/packages/flutter_secure_storage, and keep the expiry for 2 days instead of a week

See lib\utils\keys_storage.dart

**Comment by keyurgit45** [comment]
![image](https://user-images.githubusercontent.com/75253653/135763927-517326a4-781a-4a33-a429-75381825e24b.png)

I have written this code, when should we call writeCurrentSessionTime() ? @Mohitmadhav 
we can write a new timestamp we user open the app but if we want to write when user exits the app , dispose method can't be used. so need to find another way

**Comment by Mohitmadhav** [comment]
> ![image](https://user-images.githubusercontent.com/75253653/135763927-517326a4-781a-4a33-a429-75381825e24b.png)
> 
> I have written this code, when should we call writeCurrentSessionTime() ? @Mohitmadhav we can write a new timestamp we user open the app but if we want to write when user exits the app , dispose method can't be used. so need to find another way


@keyurgit45 it's better to call writeCurrentSesionTime() when the user logs in .
After that, we should call checkForExpiredSession every time the user opens the app again. 
If diff>2, then the user will be logged out. 
Then the user will have to sign in again, after which, the writeCurrentSessionTime() will be called again to store the current login time.

**Comment by keyurgit45** [comment]
means you want, the user should sign-in in every 2 days?

**Comment by Mohitmadhav** [comment]
> means you want, the user should sign-in in every 2 days? @Mohitmadhav

Actually, if the user does not open the app for more than 2 days, then he should sign in again.

**Comment by keyurgit45** [comment]
> > means you want, the user should sign-in in every 2 days? @Mohitmadhav
> 
> Actually, if the user does not open the app for more than 2 days, then he should sign in again.

ok got it

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav I have made the changes. Log in and log out are working fine. also in the sign-in method, I added the makeUserDataFromAuthUser() method which I forgot to add in prev PR. the issue #106 is due to this. I am really sorry for that. but I haven't implemented that expiry time for logging because I don't know how to implement that. Should I make a PR?

If you resolved #106 too, then mention it in your final PR, and then I'll assign #106 also to you.

**Comment by keyurgit45** [comment]
@Mohitmadhav Okay...firstly I will make PR for login and logout and then for issue #106

**Comment by keyurgit45** [comment]
![image](https://user-images.githubusercontent.com/75253653/135791672-8c00491a-0f21-4150-b26b-053cf2d9f119.png)

after doing git pull upstream main, I am getting this. I need onAuthStateChanged method, what to do here? @Mohitmadhav

**Comment by Mohitmadhav** [comment]
can you show the complete screenshot once?

**Comment by keyurgit45** [comment]
![image](https://user-images.githubusercontent.com/75253653/135794129-6348c85b-13c1-48a1-9454-da5a02f51c02.png)

**Comment by Mohitmadhav** [comment]
Ok cool, accept the incoming changes then.
