### ISSUE TITLE
Profile Tab not loading

### ISSUE THREAD

**Issue by Samveg12** [Project-Easter/Flutter-UI#106]
## Description
When we click on the profile button in the bottom navigation bar it doesnt loaf
## Screenshots
<img width="330" alt="Screenshot 2021-10-03 at 2 57 28 PM" src="https://user-images.githubusercontent.com/68071531/135747833-7d1fdf40-5263-4336-81b0-6765a61a52ba.png">

## Steps to Reproduce
Click on the profile tab in the bottom navigation bar
1. Check the provider folder - lib\providers
2. Profile page: lib\screens\profile\private_profile.dart
3. Auth files: lib\services\auth.dart

## Additional data
None

**Comment by Mohitmadhav** [comment]
> ## Description
> When we click on the profile button in the bottom navigation bar it doesnt loaf
> 
> ## Screenshots
> Upload the current working screenshots here.
> 
> ## Steps to Reproduce
> Click on the profile tab in the bottom navigation bar
> 
> 1. step 1
> 
> <img alt="Screenshot 2021-10-03 at 2 57 28 PM" width="330" src="https://user-images.githubusercontent.com/68071531/135747833-7d1fdf40-5263-4336-81b0-6765a61a52ba.png">
> 
> 1. step 2
> 2. And so on...
> 
> ## Additional data
> Anything else you want to add.

It's loading actually if you signed in through google
try out:

 - git pull upstream main
 - flutter clean
 - flutter packages get

**Comment by Mohitmadhav** [comment]
@keyurgit45 now you can work on this issue. The Email Login is done.
We can check it again after 3 days for checking auto-logout. 
Till you resolve this, the forgot password issue will be created.

**Comment by keyurgit45** [comment]
ok assign me

**Comment by keyurgit45** [comment]
@Mohitmadhav On the register page, there are only two fields email and password. So on the profile page, It shows "your name" instead of the actual name bcoz we haven't taken it from the user during registration. is it what is supposed to happen? or I'm missing something

**Comment by Mohitmadhav** [comment]
Yeah, actually I removed the Username page from the app as the Username was being retrieved from the function below during Google Login...

![Screenshot (1524)](https://user-images.githubusercontent.com/59333817/135815375-dcd0c236-72e7-4fff-a63a-cab3f41201e2.png)

But can this be achieved in a similar way for Email Login/Register in Firebase?

**Comment by keyurgit45** [comment]
We can take username while registering/sign up and we can overload this method by adding username as argument and add to the database.

**Comment by Mohitmadhav** [comment]
Yes, @keyurgit45 that is feasible, you should cover all the entries for Email Login/Register as it is done for Google Login in the above image.

**Comment by keyurgit45** [comment]
> Yes, @keyurgit45 that is feasible, you should cover all the entries for Email Login/Register as it is done for Google Login in the above image.

OK so I will add a field for name and phone number while register/sign up. and what about emailvarified and photo URL ? can you make all this a new issue? It will be easy

**Comment by keyurgit45** [comment]
![Screenshot_20211005_102304_com.example.books_app.jpg](https://user-images.githubusercontent.com/75253653/135962275-9b256893-94e5-4b2f-9e47-8d5f56228849.jpg)

**Comment by Mohitmadhav** [comment]
Cool @keyurgit45 I think we can call the same function for Email Login/Register. 
Don't do anything for the photo URL, it will be set by default.

**Comment by Mohitmadhav** [comment]
> <img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135962275-9b256893-94e5-4b2f-9e47-8d5f56228849.jpg">	<img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135964557-32d10d6a-e4a6-4c4a-9556-dbd25962fdfc.jpg">	<img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135964570-2c2ad92f-d0b4-404a-b7b3-de95e53e9c00.jpg">
> @Mohitmadhav can you please check if fields are added to the database successfully or not.

Good @keyurgit45, you called the same function, right?(Which I mentioned in the screenshot)

**Comment by keyurgit45** [comment]
![image](https://user-images.githubusercontent.com/75253653/135965412-cadefcb9-1617-45d2-800b-d48177fa76b3.png)

yeah. actually did some small changes

**Comment by Mohitmadhav** [comment]
> <img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135962275-9b256893-94e5-4b2f-9e47-8d5f56228849.jpg">	<img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135964557-32d10d6a-e4a6-4c4a-9556-dbd25962fdfc.jpg">	<img alt="" width="270" height="480" src="https://user-images.githubusercontent.com/75253653/135964570-2c2ad92f-d0b4-404a-b7b3-de95e53e9c00.jpg">
> @Mohitmadhav can you please check if fields are added to the database successfully or not.

Yes they are added in the Auth and Cloud Firestore user collection

**Comment by keyurgit45** [comment]
should I make it final?

**Comment by Mohitmadhav** [comment]
> ![image](https://user-images.githubusercontent.com/75253653/135965412-cadefcb9-1617-45d2-800b-d48177fa76b3.png)
> 
> yeah. actually did some small changes

Ok cool @keyurgit45

**Comment by Mohitmadhav** [comment]
Yes, now you can create the PR, and I'll review it
