### ISSUE TITLE
Bookmark not working (Provider State Management)

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#108]
## Description
The Books should get saved in the **Saved Books** section, once the user bookmarks them but it's not functional right now.

## Screenshots
<div class = "row">
<img src="https://user-images.githubusercontent.com/59333817/135750654-bb73fff5-4f56-49bc-8566-497d2ac4f598.png" width=45% />
<img src="https://user-images.githubusercontent.com/59333817/135750625-e9e0a6c5-446c-430b-8551-454384dad127.png" width=45% />
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Check the book provider file: lib\providers\books.dart
2. Book description file: lib\screens\book_desciption.dart
2. Other provider files: lib\providers
3. Try out by adding a Book from Google Books API then saving it as a bookmark for testing.
4. For that checkout: lib\screens\add_book.dart

## Additional data
Add the screenshots of the saved books while making the pull request.

**Comment by Samveg12** [comment]
Please assign me this issue

**Comment by Mohitmadhav** [comment]
Sure @Samveg12 !! Just make sure to follow the README properly.

**Comment by Samveg12** [comment]
Hi Mohit since I am new to this can u please help me reproduce this issue?

**Comment by Samveg12** [comment]
Like how do i get this landing page of the screen shot of the book you have put. Every book opens in form of a webview when I click on it

**Comment by Samveg12** [comment]
Also I removed the assignment accidentally please re-assign me this

**Comment by Mohitmadhav** [comment]
Okay @Samveg12 
 
- Firstly do *git pull upstream main*
 - Then go to the Profile page, and add your book.
 - Only books from Google Books API can be added. The booklist is: https://www.googleapis.com/books/v1/volumes?q=isbn
 - After adding your book it will appear on the Library page
 - Then click on it and try to bookmark. It won't work
 - Similarly, you can add many books from the above Google books API link and try to bookmark.

**Comment by Samveg12** [comment]
Hi @Mohitmadhav I think the add book one function isnt working properly due to which the book isnt being added. Am I making a mistake or is it buggy and you want me to debug that as well?
<img width="618" alt="Screenshot 2021-10-04 at 3 36 34 PM" src="https://user-images.githubusercontent.com/68071531/135833380-fcc1bd1f-ecd5-44a9-a6b1-9a9e9348ab64.png">
d

**Comment by Mohitmadhav** [comment]
It should only add books present in the google books API, but some book images due to which the API is causing a glitch.
But you should surely debug to check.

I removed some of the debug code because the actual code shouldn't contain the debugging.
You can try debugging !!!

**Comment by Samveg12** [comment]
Hi @Mohitmadhav please check the ss below the book should be in both owned and saved section or only saved section
<img width="1010" alt="Screenshot 2021-10-04 at 11 49 35 PM" src="https://user-images.githubusercontent.com/68071531/135903627-a02edec5-4450-42cb-9f69-bdcb43736fd5.png">

**Comment by Mohitmadhav** [comment]
Yes @Samveg12, once you bookmark it should be added to the saved books section.
You must have added it through the *Add your book* section.
