### ISSUE TITLE
Firebase Chat

### ISSUE THREAD

**Issue by PiotrBlachnio** [Project-Easter/Flutter-UI#11]
## Description
All our chats with different individuals should be visible to us just like in WhatsApp which we can go to by clicking the logo at the navigation panel present at the bottom of the home screen. See the Screenshots.

One way of initiating chat would be (See Chat Userflows shown below): - 
- Any user can tap on the displayed books which will take them to the Book description
- Then  the user will go to the Owner's info tab which will show the owner details
- After tapping the **Exchange this book** button we should be able to start chatting with them.

## Chat Userflows
![image](https://user-images.githubusercontent.com/59333817/135713823-71c21d09-616f-4ed4-9886-2ab622c68b96.png)

## Chat Features
All our chats with different individuals should be visible to us just like in Whatsapp which we can go to by clicking the logo at the navigation panel present at the bottom of the home screen.

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135710844-34a1be37-75d7-431c-b3a7-9329c2399434.png)

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. File location: lib/screens/chat.dart
2. You can make a chat folder for all the files

## Additional Content
Open to suggestions for any other Chat UI as nothing has been implemented yet.
Design: https://www.figma.com/file/uhWQuE4EKDHR8AqH4p3eFK/Books-App?node-id=0%3A1

**Comment by wick3ds0ul** [comment]
Started working on checklist and will update the next one.

**Comment by RandyKdev** [comment]
Good day, I would like to have a shot at this.

Could some more information be given about this? like how the database is structured or will be structured for the chat section.

**Comment by Mohitmadhav** [comment]
Cool @RandyKdev. See database_services.dart and the provider folder for more details.
The Firebase collections will be structured as #92. You just need to implement the chat functionality.

**Comment by RandyKdev** [comment]
@Mohitmadhav From the above guidelines, I would like to give a suggestion on how the firebase collection for the Chat section should be structured to ease querying.


- A collection should be named "chat"

        - Every document in the "chat" collection will hold the details and messages between 2 users
        - Every document int the "chat" collection will be structured as below
                - A field named "users" which will be an array containing the user IDs of 2 users
                - A field named "createdAt", which will hold the timestamp indicating when the users starting communicating
                - A collection named "messages", which will hold the messages between those two users
                       - Every document in the "messages" collection will have the various fields:
                               - sender: will contain the user ID of the user who sent the message
                               - receiver: will contain the user ID of the user who is to receive the message
                               - message: will contain the actual text message sent
                               - createdAt: will contain the timestamp of the message (when the message was sent)
    
By structuring the database as above, It will be easy to add, update and retrieve any information concerning chats from the "chat" collection

**Comment by ankitoscar** [comment]
Hii @RandyKdev , I was thinking if we could have a sent, delivered and seen feature, just like that. Can it be implemented?

**Comment by RandyKdev** [comment]
Ok, I will complete everything before making a PR

**Comment by Mohitmadhav** [comment]
@RandyKdev I think squashing the commits in the end might work if the PR is very large

**Comment by RandyKdev** [comment]
Good day, sorry for delaying this issue for a while now. I am unassigning myself because my exams are drawing near and I won't be able to allocate enough time to this.
When it's over, if this issue is still open, then I will take it up back and continue the work I started.
