### ISSUE TITLE
Location update without tapping twice

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#112]
## Description
 - The user first taps on the floating action button
 - Then the user again taps on the logo to display the bottom modal sheet.
 - The location gets updated in the profile when the user taps on confirm.

## Screenshots
<div class = "row">
<img src="https://user-images.githubusercontent.com/59333817/135762728-309a8376-599c-4f53-92ec-0683a58cfbbe.png" width=30% />
<img src="https://user-images.githubusercontent.com/59333817/135762730-dc886fd0-c72c-4416-9493-dfd7c5c7793d.png" width=30% />
<img src="https://user-images.githubusercontent.com/59333817/135762738-c5db2359-9705-4a10-bcb1-b62ccf61fd8c.png" width=30% />
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Check Database files: lib\services\database_service.dart
2. User location file: lib\services\user_location.dart  
3. Find a way so that user should not tap on the bottom modal sheet to update location in Firebase
4. It should automatically get updated when the user firstly taps on the bottom navigation button.
5. Can it be achieved using the same API? Or which free API can we use to add location in the user collection in Firebase?

## Additional data
 - Mapbox API has been used for location retrieval. 
 - Make sure to follow guidelines in the README
 - Send the updated screenshots in the PR if possible.

**Comment by keyurgit45** [comment]
I would like to give it a try! the map screen (2nd image) should be shown or not?

**Comment by Mohitmadhav** [comment]
Cool @kshitij5 just go through the issue and README guidellines carefully.
