### ISSUE TITLE
Flutter Test file errors 

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#132]
## Description
Flutter testing file i.e. default_test.dart has started throwing errors in the latest flutter version 2.5.

## Screenshots
<div class ="row"> 
<img src ="https://user-images.githubusercontent.com/59333817/136575208-54add547-3cb9-46b5-9ce2-46c28ea4ad0c.png" width = 60%/>
<img src ="https://user-images.githubusercontent.com/59333817/136575316-9eb6781d-06ee-4c88-8b9e-4230a21159ee.png" width = 35%/>
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. File location: test\default_test.dart
2. Do not downgrade any dependencies because the app has to be migrated to null safety later with the latest updates
3. Also look into the error  for the latest Flutter 2.5:
The plugin `geocoder` uses a deprecated version of the Android embedding.
To avoid unexpected runtime failures or future build failures, try to see if this plugin supports the Android V2
embedding. Otherwise, consider removing it since a future release of Flutter will remove these deprecated APIs.
If you are plugin author, take a look at the docs for migrating the plugin to the V2 embedding:
https://flutter.dev/go/android-plugin-migration.

## Additional data
We can discuss the further improvements here.

**Comment by aryang117** [comment]
Hey, I did look into the `geocoder` issue, and as of right now, it seems to be unsolvable. The entire plugin/package seems to be out-of-date which is causing the build errors. Also, `geocoder`'s repository seems to have gone stale (i.e, no developments/activity)
So, either we -
1. re-write the entire plugin and upgrade it to Android V2 or,
2. leave it as is or,
3. find an alternative package/plugin (which might end up being it's own issue).
@Mohitmadhav

**Comment by Mohitmadhav** [comment]
@aryang117 we can discuss it on #91.
I'll tag you there. Because we need null safety too, in future
