### ISSUE TITLE
Unfocus all the textfields in the app

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#137]
## Description
All the text fields should get dismissed when users type their entries. Check https://flutterigniter.com/dismiss-keyboard-form-lose-focus/. Look for all the text fields in the entire app which are not shown in this screenshot.

## Screenshots
<div class ="row"> 
<img src ="https://user-images.githubusercontent.com/59333817/136598085-e7257f59-26d1-4640-80d9-ea531fbf2f82.png" width = 30%/>
<img src ="https://user-images.githubusercontent.com/59333817/136598344-16260909-086b-4d62-8173-0572969e397e.png" width = 30%/>
<img src ="https://user-images.githubusercontent.com/59333817/136598393-99d72855-5715-4657-b29c-6e8a8fa08f73.png" width = 30%/>
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Initial Screen: lib\screens\initial_screen.dart
2. Auth Screens: lib\screens\auth
3. Add your book:  lib\screens\add_book.dart
4. Look for other files too.

## Additional data
Add a screen recording of keyboard dismissal of any screen in your PR.

**Comment by keyurgit45** [comment]
> Okay @keyurgit45,  but your reply isn't showing here on Github

Actually it is very easy issue so if any beginner wants to try he can try so I deleted my comment

**Comment by lalit-commits** [comment]
Hey @Mohitmadhav  ,I would like to work on this issue ,please assign it to me
