### ISSUE TITLE
Initial Screen UI change

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#138]
## Description
Change the design of the Initial Screen (Like the green color background, or adding any vector there). The current UI is shown below.

## Screenshots
<img src = "https://user-images.githubusercontent.com/59333817/136600249-f157d455-7bc8-4690-9939-9540ec6a9eee.png" width = 50% />

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Initial Screen :lib\screens\initial_screen.dart
2. Go through the entire app and decide what design changes can be done in the initial screen.
3. Make all button sizes in the same proportion

## Additional data
Design (Not exactly same as the app): https://www.figma.com/file/uhWQuE4EKDHR8AqH4p3eFK/Books-App?node-id=0%3A1
We can have further discussions here or #90

**Comment by lalit-commits** [comment]
Hey @Mohitmadhav ,I would like to work on this issue ,please assign it to me

**Comment by aryang117** [comment]
Hey @Mohitmadhav, can I work on this?

**Comment by Mohitmadhav** [comment]
Ok @aryang117
