### ISSUE TITLE
Remove the location slider widget from User Preferences Dialog

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#25]
## Description
- Remove the location bar slider from the user preferences dialog (See the screenshot)
- This slider is already present in the settings screen.

## Current Screenshots
![image](https://user-images.githubusercontent.com/59333817/135639172-8517bbe0-3204-4b31-888f-ee58f2ef613a.png)

##Additional
*Do not* delete this widget from the entire app (Just remove it from *the user_preferences.dart* file).

**Comment by alceil** [comment]
Can i work on this?

**Comment by Mohitmadhav** [comment]
Okay @alceil

**Comment by Samveg12** [comment]
Hi @alceil are u working on this? If not then please assign me this issue

**Comment by alceil** [comment]
Im working on it

**Comment by Mohitmadhav** [comment]
> Hi @alceil are u working on this? If not then please assign me this issue

Hey, @Samveg12 you can work on other issues.
And if you want to fix a bug or feature not mentioned in the issues, you can always create an issue and tag me.
I'll add the labels and assign them to you.

**Comment by Mohitmadhav** [comment]
> Im working on it

![image](https://user-images.githubusercontent.com/59333817/135751021-42bf18ff-585f-4b20-9829-f5a6c4b8a335.png)


Hey, @alceil can you delete the location slider from the settings page too?

**Comment by alceil** [comment]
Sure

**Comment by alceil** [comment]
I have done the required changes. Can you have a look? @Mohitmadhav
