### ISSUE TITLE
Dashboard screen freezes due to shuffle method

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#38]
## Description
Sometimes, the dashboard page gets stuck due to this shuffle method of the booklist 

## Current Screenshots
![image](https://user-images.githubusercontent.com/59333817/135616707-348110e8-75d4-4c3c-ade5-30238f931d28.png)
![image](https://user-images.githubusercontent.com/59333817/135616602-b766e77b-e88a-41ec-95a1-69ae0b50fc49.png)

## Additional data
If anyone finds the same issue and knows how to fix it, then comment below. Also, add your screenshots of this issue.

**Comment by alceil** [comment]
It seems like a null error i can help solve it Can anyone assign this issue to me?

**Comment by Mohitmadhav** [comment]
> It seems like a null error i can help solve it Can anyone assign this issue to me?

@alceil you can do one issue at a time. And make sure to follow the updated guidelines in README file.

**Comment by RandyKdev** [comment]
Good day, I have created a PR regarding this issue.

I would like to work on this.

**Comment by Mohitmadhav** [comment]
Cool @RandyKdev but remember to follow the guidelines next time and create a PR after getting assigned only.
And do *git pull upstream main* before making the final commits in your PR.
Then I'll review it.

**Comment by RandyKdev** [comment]
Ok, thanks. I'll do better next time in following the guidelines of this project.
