### ISSUE TITLE
Delete all the commented files

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#47]
## Description
*Delete* all the files that are *fully* commented. An example has been shown in the screenshot.

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135605471-402de461-4dbb-4cb8-8b09-81e45101c62d.png)

## Additional data
List the names of all the files you deleted and write them in your pull request. 
Feel free to ask anything in the comments and do not *delete* any folder before asking here.

**Comment by CH1NRU5T** [comment]
Could you assign me this issue?

**Comment by HanakoK9** [comment]
I'd like to work on this issue

**Comment by Mohitmadhav** [comment]
Okay @CH1NRU5T 
Remember to do *git pull upstream main* before pushing any change from your forked repo.

**Comment by Mohitmadhav** [comment]
@CH1NRU5T any updates?

**Comment by mk1107** [comment]
hi can you assign me this task

**Comment by Mohitmadhav** [comment]
@mk1107 this issue is already resolved
And @CH1NRU5T please remember to add the issue number while making any PR from next time onwards.
