### ISSUE TITLE
Remove Confirmation Code Screen

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#56]
## Description
- Remove the confirmation code page and directly navigate the register screen to the dashboard. 
- Remove the *confirm_email.dart* file, and set the routing accordingly. (Register Page is a dummy right now, we'll make it functional through creating another issue)
-  Also remove all the functions related to the above file, like ConfirmationCodeTextField(), etc from the app as shown in the screenshot.

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135637463-fd79dbbb-fee2-4867-a0e7-77677a3dab85.png)
![image](https://user-images.githubusercontent.com/59333817/135637045-816689dd-188a-41cc-90a7-5616352bfd8e.png)

## Additional data
We can discuss this here further before making a major change.

**Comment by Mohitmadhav** [comment]
@anhhao92 firstly you should comment here and get yourselves assigned with the issue.
Then only you can create a PR.

**Comment by krish-dev-7** [comment]
would you please assign this to me

**Comment by anhhao92** [comment]
> @anhhao92 firstly you should comment here and get yourselves assigned with the issue. Then only you can create a PR.
Could you assign this issue to me

**Comment by Mohitmadhav** [comment]
> > @anhhao92 firstly you should comment here and get yourselves assigned with the issue. Then only you can create a PR.
> > Could you assign this issue to me

I didn't get you.
And please read the updated guidelines in the readme.

**Comment by keyurgit45** [comment]
Can i work on this? @Mohitmadhav

**Comment by Mohitmadhav** [comment]
@anhhao92 @krish-dev-7 please follow the guidelines given in the README before making any PR.
You can only make a PR after you get assigned.

**Comment by Mohitmadhav** [comment]
> > @anhhao92 firstly you should comment here and get yourselves assigned with the issue. Then only you can create a PR.
> > Could you assign this issue to me

@anhhao92 you can tag me on other issues to get yourselves assigned.
