### ISSUE TITLE
Edit Profile and Owner's Info tab not working (Provider State Management)

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#79]
## Description
- The Edit Profile Page isn't opening. The error is as shown below.
- Same error occurs in the book description page when tapping on *Owner's Info*
- Try it in your local system first

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135646066-2f45577f-6a3e-4648-8a71-549a20872689.png)
![image](https://user-images.githubusercontent.com/59333817/135713190-2f9c742e-0f17-41b1-83cf-d81169eac7de.png)

## Steps to Reproduce
This has occurred because the provider hasn't been registered in *main.dart*.

1. So either replace the Provider with *Stream Provider* (Initialized in *home.dart*)
2. OR  Extend the UserData function with ChangeNotifiers with relevant functions(If required)
3. User Model : lib/providers/user.dart
4. Book Description page: lib/screens/book_desciption.dart

## Additional data
What better solution can be there to fix this issue? Go through the entire codebase for more clarity.

**Comment by Mohitmadhav** [comment]
The entire error is: 

Exception has occurred.
ProviderNotFoundException (Error: Could not find the correct Provider<UserData> above this EditProfile Widget

This happens because you used a `BuildContext` that does not include the provider
of your choice. There are a few common scenarios:

- You added a new provider in your `main.dart` and performed a hot-reload.
  To fix, perform a hot-restart.

- The provider you are trying to read is in a different route.

  Providers are "scoped". So if you insert of provider inside a route, then
  other routes will not be able to access that provider.

- You used a `BuildContext` that is an ancestor of the provider you are trying to read.

  Make sure that EditProfile is under your MultiProvider/Provider<UserData>.
  This usually happens when you are creating a provider and trying to read it immediately.

  For example, instead of:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // Will throw a ProviderNotFoundError, because `context` is associated
      // to the widget that is the parent of `Provider<Example>`
      child: Text(context.watch<Example>()),
    ),
  }
  ```

  consider using `builder` like so:

  ```
  Widget build(BuildContext context) {
    return Provider<Example>(
      create: (_) => Example(),
      // we use `builder` to obtain a new `BuildContext` that has access to the provider
      builder: (context) {
        // No longer throws
        return Text(context.watch<Example>()),
      }
    ),
  }
  ```

If none of these solutions work, consider asking for help on StackOverflow:
https://stackoverflow.com/questions/tagged/flutter
)

**Comment by merelj** [comment]
I'll take a look at this one 🕵️

**Comment by Mohitmadhav** [comment]
Cool @merelj, I'm assigning it to you.
Also, once go through the whole app and see if this behavior gets repeated, and try to solve that too because all of them have the same provider path issue.

**Comment by merelj** [comment]
For now almost every page is either broken or empty whenever I start up the app: I cannot even navigate to book screen and Edit Profile Page does not have a working link to it 😕

Not sure if it has something to do with my setup, internet connection or problems with the code, but for now I don't think I have enough time on my hands to work through it without slowing you down, sorry 🙇

**Comment by Mohitmadhav** [comment]
* The Provider error is the same with these 2 pages (Profile and Owners info tab)
* And Dashboard and Library page won't be empty if you add your book through the `Add your book` button on the Profile page
* The rest empty pages have been allotted as issues to other people so don't worry about them

@merelj you try out to resolve them, and if not then you can unassign yourself and work on some other issue
