### ISSUE TITLE
Change Google Sign In button

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#82]
## Description
Change the Google sign-in button to a broader one.

## Current  Screenshots
![image](https://user-images.githubusercontent.com/59333817/135661646-2b4c7482-2031-473f-83e5-899651b0d777.png)

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Remove the Facebook button
2. Change the Google button UI using  https://pub.dev/packages/flutter_signin_button

## Additional data
None

**Comment by phan-dev** [comment]
@Mohitmadhav 
Can you assign this issue for me?

**Comment by Sayam06** [comment]
@Mohitmadhav please assign it to me

**Comment by Mohitmadhav** [comment]
@phan-dev you can work only on one issue at a time. Read the guidelines given in the README file for more details.

@Sayam06 I'm assigning it to you. And please make sure to submit the PR as per the template.

**Comment by hrigved-dev** [comment]
Hey @Mohitmadhav , I wish to contribute to this project. Please consider me for any future issues :)

**Comment by Mohitmadhav** [comment]
> Hey @Mohitmadhav, I wish to contribute to this project. Please consider me for any future issues :)

Sure @hrigved-dev, more issues will be created, you can comment and tag me before others,  for getting assigned !!
