### ISSUE TITLE
Email Authentication using Provider and Firebase

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#83]
## Description
- Setup Email Signup using Firebase and Provider State management
- #56 has already been created for removing the confirmation code page
- Auth user flow is shown below

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135663846-50ee37a7-8c02-47e7-8c25-84e60c79f851.png)

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Make an auth provider dart file in *lib\providers*
2. All the auth screens are in *lib\screens\auth*
3. Firebase Auth has been set up in *lib\services\auth.dart*

## Additional data
Auth User flow: https://www.figma.com/file/uhWQuE4EKDHR8AqH4p3eFK/Books-App?node-id=0%3A1
Maybe we can reset the password in a better way. Let's discuss it here

**Comment by keyurgit45** [comment]
Can I work on this?

**Comment by Mohitmadhav** [comment]
Cool @keyurgit45.
Also, follow the updated Guidelines in the README.

**Comment by keyurgit45** [comment]
In widgets.dart there are custom textformfields for email and password. to get the text should I use textEditingController or onchanged ? @Mohitmadhav

**Comment by Mohitmadhav** [comment]
> In widgets.dart there are custom textformfields for email and password. to get the text should I use textEditingController or onchanged ? @Mohitmadhav

@keyurgit45 use textEditingController and make sure to check the validators.
