### ISSUE TITLE
Remove Facebook Login

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#96]
## Description
Completely remove the Facebook Authentication functionalities from the app.

## Screenshots
None

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Auth files: lib/services/auth.dart
2. Remove all Facebook login commands if present in the UI.

## Additional data
None

**Comment by sarthakvaishnav09** [comment]
Hey, I would like to work on this.

**Comment by dazzlerkumar** [comment]
Hey @Mohitmadhav , You can assign this to me.
Thank You!

**Comment by pri1311** [comment]
Hey! Can I work on this issue?

**Comment by Mohitmadhav** [comment]
@sarthakvaishnav09, I assigned you another issue, so one issue at a time!!

@dazzlerkumar, I'm assigning it to you. Make sure to follow the updated guidelines mentioned in the README.

@pri1311 there'll be more issues created. You can tag me there first to get yourself assigned before anyone else.
