### ISSUE TITLE
Implement Google Sign-out 

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#98]
## Description
 - The user should log out when tapped on the **Logout** button as shown in the screenshot.
 - Currently, the user directly gets navigated to the initial screen without getting logged out.

## Screenshots
<div class = "row">
<img src="https://user-images.githubusercontent.com/59333817/135721109-4e679906-8700-4008-8b18-00b0ec383719.png" 
 width = 45% />
<img src="https://user-images.githubusercontent.com/59333817/135722346-cdf92d0c-536e-4a26-913d-b59265bab42d.png" 
  width = 45% />
</div>

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. Private profile: lib/screens/profile/private_profile.dart
2. Google Firebase Auth: lib/services/auth.dart
3. Initial Screen: lib/screens/initial_screen.dart
3. Check for the access token expiry because the user should again login after a certain period of time (Like - a few days after logging in)

## Additional data
Google Firebase auth is already setup, you just need to implement google signout.

**Comment by sarthakvaishnav09** [comment]
Hey, I would like to work on this.

**Comment by Mohitmadhav** [comment]
Okay, cool @sarthakvaishnav09.

Please make sure to follow the updated guidelines given in the README.

**Comment by sarthakvaishnav09** [comment]
@Mohitmadhav I ran into a new issue while logging in using email and password.

The getter 'uid' was called on null.

Also, the profile tab keeps on loading forever, so I'm not able to reproduce this error. (This happens when I sign up for this first time in the app, later on when I log in with the same email the error of null uid arises)

PS : The google signOut method in auth.dart seems completed already.

What should I do?

**Comment by Mohitmadhav** [comment]
> @Mohitmadhav I ran into a new issue while logging in using email and password.
> 
> The getter 'uid' was called on null.
> 
> Also, the profile tab keeps on loading forever, so I'm not able to reproduce this error. (This happens when I sign up for this first time in the app, later on when I log in with the same email the error of null uid arises)
> 
> PS : The google signOut method in auth.dart seems completed already.
> 
> What should I do?

Yeah @sarthakvaishnav09, I have assigned that issue to someone else.
You just check for google signout.

**Comment by Mohitmadhav** [comment]
![image](https://user-images.githubusercontent.com/59333817/135761273-80e6519b-5d43-41f2-8c97-31d26a7c3e65.png)


Also in the file **private_profile.dart** change the push replacement code because the user is navigating back to the Initial screen. Hope you understood.
So remove the gesture detector, and do sign out inside the onPressed function.
