### ISSUE TITLE
Linting check (Remove Warnings)

### ISSUE THREAD

**Issue by Mohitmadhav** [Project-Easter/Flutter-UI#99]
## Description
 - Remove all the warnings as shown in the screenshot below.

## Screenshots
![image](https://user-images.githubusercontent.com/59333817/135722631-9c433989-db61-4c5f-bfbc-683a8ba691ad.png)

## Steps to Reproduce
Please provide detailed steps for reproducing the issue.

1. See analysis_options.yaml for all the linting rules
2. Remove all the unused imports.
3. Update all the deprecated widgets.
4. Rectify all other kinds of warnings by following standard practices.

## Additional data
I'll check whether the Github actions for linting get passed or not after that.

**Comment by Mastersam07** [comment]
Please assign this to me

**Comment by Mohitmadhav** [comment]
Okay, @Mastersam07.
Please remember to follow all the updated guidelines as specified in the README

**Comment by Mohitmadhav** [comment]
@Mastersam07 do *git pull upstream main* to get the updated code.
Then finally you should resolve all the errors and warnings.

**Comment by Mohitmadhav** [comment]
@Mastersam07 any updates?

**Comment by ankitoscar** [comment]
@Mastersam07 you have not provided any updates for the last week, hence I am unassigning this issue from you.

**Comment by aryang117** [comment]
Hey @Mohitmadhav, can I work on this?

**Comment by Mohitmadhav** [comment]
Sure @aryang117

**Comment by Mohitmadhav** [comment]
It won't take much time @aryang117. Now there are around 40 warnings only

**Comment by aryang117** [comment]
@Mohitmadhav Yea, I already fixed a few of them locally. 
Once my PR for #147 gets accepted, I'll quickly commit the fixes and make the PR for this

**Comment by Mohitmadhav** [comment]
Okay @aryang117, you'll have to make it real quick.

**Comment by Mohitmadhav** [comment]
@aryang117 just remember to do ` git pull upstream main ` before making the PR.

**Comment by aryang117** [comment]
@Mohitmadhav yea I did that and already made a PR with fixes.
